#!/bin/bash
# postinst script for airtime-easy-install

set -e

if [ "$DPKG_DEBUG" = "developer" ]; then
    set -x
fi

# Set the path to the package signing key
APT_KEY=/usr/share/keyrings/sourcefabric-key

case "$1" in
  configure|reconfigure)

    # Find the distro we are installing on
    DISTRONAME=$(lsb_release -sc)

    # Replace the default with the name of the current distro
    if [ -f /etc/apt/sources.list.d/sourcefabric.list ]; then
    sed -i "s:squeeze:$DISTRONAME:g" /etc/apt/sources.list.d/sourcefabric.list
    fi

    # Install the package signing key
    apt-key add $APT_KEY

    # Get the system time zone, thanks to Müller Zsolt :-)
    area="Etc"
    zone="UTC"
     ret="$(echo get tzdata/Areas | debconf-communicate)"
      if [ $? -eq 0 ]; then
       set -- $ret
       shift
       area="$@"
       ret="$(echo get "tzdata/Zones/${area}" | debconf-communicate)"
        if [ $? -eq 0 ]; then
         set -- $ret
         shift
         zone="$@"
        fi
      fi

    echo "Setting up Airtime for ${area}/${zone} timezone..."

    # Insert the system time zone into the preseed file
    sed -i "s:Etc/UTC:${area}/${zone}:g" /usr/share/airtime/debconf-selections

    echo "Now running airtime-easy-install script..."
    mkdir -p /var/log/airtime
    nohup /usr/bin/airtime-easy-install > /var/log/airtime/airtime-easy-install &
    disown -h

  ;;

  abort-upgrade|abort-remove|abort-deconfigure)

  ;;

  *)
       echo "postinst called with unknown argument \`$1'" >&2
       exit 1
  ;;
esac

#DEBHELPER#

exit 0
