#!/bin/bash
# postinst script for airtime-easy-install

set -e

if [ "$DPKG_DEBUG" = "developer" ]; then
    set -x
fi

# Set the path to the package signing key
APT_KEY=/usr/share/keyrings/sourcefabric-key

case "$1" in
  configure|reconfigure)

    # Find the distro we are installing on
    DISTRONAME=$(lsb_release -sc)

    # Replace the default with the name of the current distro
    if [ -f /etc/apt/sources.list.d/sourcefabric.list ]; then
    sed -i "s:squeeze:$DISTRONAME:g" /etc/apt/sources.list.d/sourcefabric.list
    fi

    # Install the package signing key
    apt-key add $APT_KEY

    # Get the system time zone
    tmpfile=$(mktemp)
     if [ -f "${tmpfile}" -a -w "${tmpfile}" ]; then
      debconf-get-selections > "${tmpfile}"
       set -- $(egrep '^tzdata[[:space:]]+tzdata/Areas[[:space:]]+select[[:space:]]+[^[:space:]]' "${tmpfile}")
       while [ -n "$1" ]; do area="$1"; shift; done
       set -- $(egrep "^tzdata[[:space:]]+tzdata/Zones/${area}[[:space:]]+select[[:space:]]+[^[:space:]]" "${tmpfile}")
       while [ -n "$1" ]; do zone="$1"; shift; done
       SYSTEMTIMEZONE="${area}/${zone}"
       rm "${tmpfile}"
     else
      echo "error: failed to create tempfile" >&2
     fi

    # Insert the system time zone into the preseed file
    sed -i "s:Etc/UTC:$SYSTEMTIMEZONE:g" /usr/share/airtime/debconf-selections

    echo "Now running airtime-easy-install..."
    mkdir -p /var/log/airtime
    nohup /usr/bin/airtime-easy-install > /var/log/airtime/airtime-easy-install &
    disown -h

  ;;

  abort-upgrade|abort-remove|abort-deconfigure)

  ;;

  *)
       echo "postinst called with unknown argument \`$1'" >&2
       exit 1
  ;;
esac

#DEBHELPER#

exit 0
