#!/bin/bash
# postinst script for airtime-easy-install

set -e

if [ "$DPKG_DEBUG" = "developer" ]; then
    set -x
fi

case "$1" in
  configure|reconfigure)

    # Find the distro we are installing on
    DISTRONAME=$(lsb_release -sc)

    # Replace the default with the name of the current distro
    if [ -f /etc/apt/sources.list.d/sourcefabric.list ]; then
    sed -i "s:squeeze:$DISTRONAME:g" /etc/apt/sources.list.d/sourcefabric.list
    fi

    echo "Reload the package list, as we have changed it"
    apt-get update

    echo "Install the package signing key"
    #apt-get -y install sourcefabric-keyring

    echo "Reload the package list again, to use secure apt"
    #apt-get update

    echo "Install the apps"
    #apt-get -y install postgresql icecast2 airtime

  ;;

  abort-upgrade|abort-remove|abort-deconfigure)

  ;;

  *)
       echo "postinst called with unknown argument \`$1'" >&2
       exit 1
  ;;
esac

#DEBHELPER#

exit 0
