#!/bin/bash
# postinst script for airtime-easy-setup

set -e

if [ "$DPKG_DEBUG" = "developer" ]; then
    set -x
fi

# Set the path to the package signing key
APT_KEY=/usr/share/keyrings/airtime-easy-setup-key

case "$1" in
  configure|reconfigure)

    # Find the distro we are installing on
    DISTRONAME=$(lsb_release -sc)

    # Replace the squeeze repo with the correct repo if we are running Ubuntu or Wheezy
    if [ "$DISTRONAME" != "squeeze" ]; then
     if [ -f /etc/apt/sources.list.d/sourcefabric.list ]; then
      sed -i "2s:squeeze:$DISTRONAME:g" /etc/apt/sources.list.d/sourcefabric.list
     fi
    fi

    # Set up multimedia repo if we are running Debian squeeze rather than Ubuntu or Wheezy
    if [ "$DISTRONAME" = "squeeze" ]; then
     if [ -f /etc/apt/sources.list.d/sourcefabric.list ]; then
      sed -i "5s:#deb:deb:g" /etc/apt/sources.list.d/sourcefabric.list
     fi
    fi

    # Install the Sourcefabric package signing key
    if [ ! -f /usr/share/keyrings/sourcefabric-key ]; then
     echo "Installing Sourcefabric package signing key..."
     apt-key add $APT_KEY
    fi

    # Get the system time zone, thanks to Müller Zsolt :-)
    area="Etc"
    zone="UTC"
     ret="$(echo get tzdata/Areas | debconf-communicate)"
      if [ $? -eq 0 ]; then
       set -- $ret
       shift
       area="$@"
       ret="$(echo get "tzdata/Zones/${area}" | debconf-communicate)"
        if [ $? -eq 0 ]; then
         set -- $ret
         shift
         zone="$@"
        fi
      fi

    echo "Setting up Airtime for ${area}/${zone} timezone..."

    # Insert the system time zone into the preseed file
    sed -i "s:Etc/UTC:${area}/${zone}:g" /usr/share/airtime/debconf-selections

    # Get the fully qualified domain name of the server
    DOMAINNAME=$(hostname --fqdn)

    echo "Setting Icecast and Airtime domain names to $DOMAINNAME..."

    # Insert the domain name into the preseed file
    sed -i "s:localhost:$DOMAINNAME:g" /usr/share/airtime/debconf-selections

    echo "Setting defaults for non-interactive installation..."
    debconf-set-selections /usr/share/airtime/debconf-selections

    # Check that the server has a UTF-8 locale
    update-locale
    DEFAULTLOCALE=$(cat /etc/default/locale | sed -e "s:LANG=::g")
    if [[ "$DEFAULTLOCALE" = *"UTF-8" ]]; then
    echo -e "$DEFAULTLOCALE is the default locale on this server and appears to support UTF-8 encoding."
    echo -e "\n Now please run the commands:"

    else
    echo -e "\n Warning: Your server's default locale $DEFAULTLOCALE may not support UTF-8 encoding, please check it!"
    echo -e "\n Airtime requires a UTF-8 locale to run. If you need to fix this, please run the following commands:"

         if [ "$DISTRONAME" != "squeeze" -a "$DISTRONAME" != "wheezy" ]; then
         echo -e "\n   sudo locale-gen ru_RU.UTF-8"
         echo -e "\n   sudo update-locale LANG=ru_RU.UTF-8"
         echo -e "\n where ru_RU.UTF-8 is the UTF-8 version of your locale (Russian, in this example)."
         echo -e "\n A list of supported locales is available in the file /usr/share/i18n/SUPPORTED"
         echo -e "\n You may need to log out from the server and log back in for the change to take effect."
         fi

         if [ "$DISTRONAME" = "squeeze" -o "$DISTRONAME" = "wheezy" ]; then
         echo -e "\n   sudo dpkg-reconfigure locales"
         echo -e "\n and select the UTF-8 version of your locale, for example ru_RU.UTF-8 for Russian."
         echo -e "\n On the second page, select this new locale as the default."
         echo -e "\n You may need to log out from the server and log back in for the change to take effect."
         fi

    echo -e "\n Once these changes have been made, please run the commands:"
    fi

    echo -e "\n   sudo apt-get update \n   sudo apt-get install airtime"
    echo -e "\n After that, installation of Airtime should be complete in a couple of minutes."
    echo -e "\n You should then be able to log in to Airtime at http://$DOMAINNAME/"

  ;;

  abort-upgrade|abort-remove|abort-deconfigure)

  ;;

  *)
       echo "postinst called with unknown argument \`$1'" >&2
       exit 1
  ;;
esac

#DEBHELPER#

exit 0
