#!/bin/bash
# postinst script for airtime-easy-install

set -e

if [ "$DPKG_DEBUG" = "developer" ]; then
    set -x
fi

# Set the path to the package signing key
APT_KEY=/usr/share/keyrings/airtime-easy-setup-key

case "$1" in
  configure|reconfigure)

    # Find the distro we are installing on
    DISTRONAME=$(lsb_release -sc)

    # Replace the Debian repo with the correct repo if we are running Ubuntu
    if [ "$DISTRONAME" != "squeeze" ]; then
     if [ -f /etc/apt/sources.list.d/sourcefabric.list ]; then
      sed -i "2s:squeeze:$DISTRONAME:g" /etc/apt/sources.list.d/sourcefabric.list
     fi
    fi

    # Set up multimedia repo if we are running Debian stable rather than Ubuntu
    if [ "$DISTRONAME" = "squeeze" ]; then
     if [ -f /etc/apt/sources.list.d/sourcefabric.list ]; then
      sed -i "5s:#deb:deb:g" /etc/apt/sources.list.d/sourcefabric.list
     fi
    fi

    # Install the Sourcefabric package signing key
    if [ ! -f /usr/share/keyrings/sourcefabric-key ]; then
     echo "Installing Sourcefabric package signing key..."
     apt-key add $APT_KEY
    fi

    # Get the system time zone, thanks to Müller Zsolt :-)
    area="Etc"
    zone="UTC"
     ret="$(echo get tzdata/Areas | debconf-communicate)"
      if [ $? -eq 0 ]; then
       set -- $ret
       shift
       area="$@"
       ret="$(echo get "tzdata/Zones/${area}" | debconf-communicate)"
        if [ $? -eq 0 ]; then
         set -- $ret
         shift
         zone="$@"
        fi
      fi

    echo "Setting up Airtime for ${area}/${zone} timezone..."

    # Insert the system time zone into the preseed file
    sed -i "s:Etc/UTC:${area}/${zone}:g" /usr/share/airtime/debconf-selections

    # Get the fully qualified domain name of the server
    DOMAINNAME=$(hostname --fqdn)

    echo "Setting Icecast and Airtime domain names to $DOMAINNAME..."

    # Insert the domain name into the preseed file
    sed -i "s:localhost:$DOMAINNAME:g" /usr/share/airtime/debconf-selections

    echo "Setting defaults for non-interactive installation..."
    debconf-set-selections /usr/share/airtime/debconf-selections

    echo -e "\n Now please run the commands: \n   sudo apt-get update \n   sudo apt-get install airtime"
    echo -e "\n After that, installation of Airtime should be complete in a couple of minutes."
    echo -e "\n You should then be able to log in to Airtime at http://$DOMAINNAME/"

  ;;

  abort-upgrade|abort-remove|abort-deconfigure)

  ;;

  *)
       echo "postinst called with unknown argument \`$1'" >&2
       exit 1
  ;;
esac

#DEBHELPER#

exit 0
